// <auto-generated />
using AuthenticateMicroservice.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticateMicroservice.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20220708142136_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthenticateMicroservice.Models.UserCredentails", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.ToTable("clientList");

                    b.HasData(
                        new
                        {
                            UserName = "Manager",
                            Password = "1234",
                            Roles = "Employee"
                        },
                        new
                        {
                            UserName = "JhonSmith",
                            Password = "0000",
                            Roles = "Customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
